// Code generated by goctl. DO NOT EDIT.
package types

type Task struct {
	Id          int64  `json:"id"`
	TaskId      string `json:"task_id"`
	Action      string `json:"action"`
	Index       int64  `json:"index"`
	Prompt      string `json:"prompt"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type FetchReq struct {
	ID     int64  `form:"id"`
	TaskId string `form:"task_id"` //任务ID
}

type FetchResp struct {
	TaskInfo Task `json:"task_info"`
}

type ListReq struct {
}

type ListResp struct {
	List []Task `json:"list"`
}

type ImagineReq struct {
	Prompt string `json:"prompt"`
}

type ImagineResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type UpscaleReq struct {
	TaskId string `json:"task_id"`
	Index  int64  `json:"index"`
}

type UpscaleResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type VariationReq struct {
	TaskId string `json:"task_id"`
	Index  int64  `json:"index"`
}

type VariationResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
