// Code generated by goctl. DO NOT EDIT.
package types

type Task struct {
	Id          int64  `json:"id"`
	TaskId      string `json:"task_id,optional"`
	Action      string `json:"action,options=[IMAGINE,UPSCALE,VARIATION]"`
	Index       int64  `json:"index,optional"`
	Prompt      string `json:"prompt,optional"`
	Description string `json:"description,optional"`
	ImageUrl    string `json:"image_url,optional"`
	Status      string `json:"status,options=[PENDING,SUCCESS]"`
	CreatedAt   int64  `json:"created_at,optional"`
	UpdatedAt   int64  `json:"updated_at,optional"`
}

type FetchReq struct {
	ID     int64  `form:"id,optional"`
	TaskId string `form:"task_id,optional"` //任务ID
}

type FetchResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data Task   `json:"data"`
}

type ListReq struct {
}

type ListResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data []Task `json:"data"`
}

type ImagineReq struct {
	Prompt string `json:"prompt"`
}

type ImagineResp struct {
	Code int64                  `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type UpscaleReq struct {
	TaskId string `json:"task_id"`
	Index  int64  `json:"index"`
}

type UpscaleResp struct {
	Code int64                  `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type VariationReq struct {
	TaskId string `json:"task_id"`
	Index  int64  `json:"index"`
}

type VariationResp struct {
	Code int64                  `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}
