// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/ParkerWen/wechat_pro/app/wecom/midjourney/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/imagine",
				Handler: imagineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upscale",
				Handler: upscaleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/variation",
				Handler: variationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify",
				Handler: notifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/callback",
				Handler: callbackGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/callback",
				Handler: callbackPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendTextNoticeTemplateCard",
				Handler: sendTextNoticeTemplateCardHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendButtonInteractionTemplateCard",
				Handler: sendButtonInteractionTemplateCardHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uploadTempFile",
				Handler: uploadTempFileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/wecom/midjourney/v1"),
	)
}
