// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/ParkerWen/wechat_pro/app/midjourney/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/email/register",
				Handler: registerByEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/email/login",
				Handler: loginByEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/phone/register",
				Handler: registerByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/phone/login",
				Handler: loginByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: generateTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/mj/user/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fetch",
				Handler: fetchHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/mj/user/v1"),
	)
}
