// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/ParkerWen/wechat_pro/app/callback/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/callback",
				Handler: CallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/callback",
				Handler: RecvHandler(serverCtx),
			},
		},
	)
}
